version: '3.7'
services:
  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      # KAFKA_ADVERTISED_PORT: 9092
      # KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: "-Xmx215M -Xms215M"
      JMX_PORT: 9999 
    volumes:
      # - ./kafka1/logs:/kafka
      - ./kafka1:/kafka
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    depends_on:
      - zoo1
      # - zoo2
      # - zoo3
    networks:
      web-php-net:
        ipv4_address: 172.25.0.36

  # kafka2:
  #   image: wurstmeister/kafka
  #   restart: always
  #   hostname: kafka2
  #   container_name: kafka2
  #   ports:
  #     - "9093:9092"
  #   environment:
  #     KAFKA_LISTENERS: PLAINTEXT://kafka2:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:218
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     JMX_PORT: 9988
  #   volumes:
  #     - ./kafka2:/kafka
  #     - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
  #   depends_on:  # 连接本compose文件以外的container
  #     - zoo1
  #     - zoo2
  #     - zoo3
  #   networks:
  #     web-php-net:
  #       ipv4_address: 172.25.0.37

  # kafka3:
  #   image: wurstmeister/kafka
  #   restart: always
  #   hostname: kafka3
  #   container_name: kafka3
  #   ports:
  #     - "9094:9092"
  #   environment:
  #     KAFKA_LISTENERS: PLAINTEXT://kafka3:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:218
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     JMX_PORT: 9977
  #   volumes:
  #     - ./kafka3:/kafka
  #     - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
  #   depends_on:  # 连接本compose文件以外的container
  #     - zoo1
  #     - zoo2
  #     - zoo3
  #   networks:
  #     web-php-net:
  #       ipv4_address: 172.25.0.39     

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: always
    container_name: kafka-manager
    hostname: kafka-manager
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    ports:
      - "9002:9000"
    # depends_on:           # 连接本compose文件创建的container
    # external_links:   # 连接本compose文件以外的container
    depends_on:
      - zoo1
      - kafka1
      # - kafka2
      # - kafka3
      # - zoo2
      # - zoo3
    environment:
      # ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
      # KAFKA_BROKERS: kafka1:9092,kafka2:9093,kafka3:9094
      ZK_HOSTS: zoo1:2181
      KAFKA_BROKERS: kafka1:9092
      # APPLICATION_SECRET: letmein
      # KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
      web-php-net:
        ipv4_address: 172.25.0.38 
        
  zoo1:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
    volumes:
      - "./zoo1/data:/data"
      - "./log/zoo1/datalog:/datalog"
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      ZOO_MY_ID: 1
      # ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      ZOO_SERVERS: server.1=zoo1:2888:3888
    networks:
      web-php-net:
        ipv4_address: 172.25.0.30
  # zoo2:
  #   image: zookeeper
  #   restart: always
  #   hostname: zoo2
  #   container_name: zoo2
  #   ports:
  #     - 2180:2181
  #   volumes:
  #     - "./zoo2/data:/data"
  #     - "./log/zoo2/datalog:/datalog"
  #     - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
  #   environment:
  #     ZOO_MY_ID: 2
  #     ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  #   networks:
  #     web-php-net:
  #       ipv4_address: 172.25.0.31

  # zoo3:
  #   image: zookeeper
  #   restart: always
  #   hostname: zoo3
  #   container_name: zoo3
  #   ports:
  #     - 2179:2181
  #   volumes:
  #     - "./zoo3/data:/data"
  #     - "./log/zoo3/datalog:/datalog"
  #     - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
  #   environment:
  #     ZOO_MY_ID: 3
  #     ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  #   networks:
  #     web-php-net:
  #       ipv4_address: 172.25.0.32

# #设置内部网络        
# networks:
#   # lnmp-env:
#   #   driver: bridge
#   web-php-net:
#     driver: bridge
#     ipam:
#       config:
#        - subnet: 172.25.0.0/16
#使用外部网络  docker network create --driver bridge --subnet 172.25.0.0/24 --gateway 172.25.0.1 web-php-net
networks:
  web-php-net:
   external:
      name: web-php-net      

#volumes:
    #db-data:
volumes:
  esdata:
    driver: local
  mysqldata:
    driver: local
  mysqllog:
    driver: local
  redisdata:
    driver: local    
