version: '3.7'
services:
  nginx:
    image: openresty/openresty:alpine
    # image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
        #- "443:443"
    expose:
      - "80"
    depends_on:
      - redis
      - php  
   # deploy:
   #   replicas: 2
   #   update_config:
   #     parallelism: 2
   #     delay: 10s
   #     order: start-first    
   # external_links:
   #   - php:fpm
    restart: always
    networks:
      - "lnmp-env"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./conf/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:rw
      # - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
        #- ./conf/nginx/mime.types:/etc/nginx/mime.types:rw
      - ./log/nginx/:/var/log/nginx/:rw
  php:
    image: ligang7138/php7.3-fpm-alpine1
    #build: ./php/php72/
    container_name: php-7.3
    ports:
      - "9000:9000"      
    # expose:
      # - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      # - ./conf/php/php.ini:/usr/local/etc/php/php.ini:rw
      # - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    #external_links:
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - "lnmp-env"
  mysql:
    image: mariadb:latest
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:rw
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    restart: always
    networks:
      - "lnmp-env"
  #redis单机
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"    
  # redis-cluster:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
    networks:  
      - "lnmp-env"
  
networks:
  lnmp-env:
    driver: bridge

#volumes:
    #db-data:
