FROM docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.2

LABEL maintainer="445123875@qq.com"

COPY ./config/elasticsearch.yml /usr/share/elasticsearch/conifg/elasticsearch.yml

RUN echo "Asia/Shanghai" > /etc/timezone